version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
    - "automated-pr"
    groups:
      actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/Tests/ExamplesTest"
      - "/ci/run_tests"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
    - "automated-pr"
    groups:
      pip-dependencies:
        patterns:
          - "*"
