version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
    - "automated-pr"
    group:
      name: "GitHub Actions"
      package-ecosystem: "github-actions"

  - package-ecosystem: "pip"
    directories:
      - "/Tests/ExamplesTest"
      - "/ci/run_tests"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
    - "automated-pr"
    group:
      name: "pip updates"
      package-ecosystem: "pip"
