env:
  BUILD_DIR: "build"

task:
  name: Test FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-12-3
      image_family: freebsd-13-0
  install_script:
    - pkg install -y libpcap bash gsed gmake tcpreplay
  configure_script:
    - ./configure-freebsd.sh --default
  build_script:
    - gmake all
  test_pcapplusplus_script:
    - ifconfig vtnet0 promisc
    - python -m ensurepip
    - python -m pip install -r ci/run_tests/requirements.txt
    - python ci/run_tests/run_tests.py --interface vtnet0
  test_examples_script:
    - cd Tests/ExamplesTest
    - python -m ensurepip
    - python -m pip install -r requirements.txt
    - python -m pytest --interface vtnet0 --use-sudo

  name: Test FreeBSD w/ CMake
  freebsd_instance:
    matrix:
      image_family: freebsd-12-3
      image_family: freebsd-13-0
  install_script:
    - pkg install -y bash cmake git gmake gsed libpcap tcpreplay
  configure_script:
    - cmake -S . -B Dist
  build_script:
    - cmake --build Dist -j 2
  test_pcapplusplus_script:
    - ifconfig vtnet0 promisc
    - python -m ensurepip
    - python -m pip install -r ci/run_tests/requirements.txt
    - python ci/run_tests/run_tests.py --interface vtnet0
  test_examples_script:
    - cd Tests/ExamplesTest
    - python -m ensurepip
    - python -m pip install -r requirements.txt
    - python -m pytest --interface vtnet0 --use-sudo --root-path=../../Dist/examples_bin

task:
  name: Test Zstd Linux
  container:
    image: seladb/ubuntu2004-zstd:latest
  configure_script:
    - ./configure-linux.sh --use-zstd
    - ldconfig
  build_script:
    - make all
  test_pcapplusplus_script:
    - python3 -m pip install -r ci/run_tests/requirements.txt
    - python3 ci/run_tests/run_tests.py --interface eth0

task:
  name: Test Zstd Linux w/ CMake
  container:
    image: seladb/ubuntu2004-zstd:latest
  configure_script:
    - cmake -DLIGHT_PCAPNG_ZSTD=ON -S . -B Dist
  build_script:
    - cmake --build Dist -j 2
  test_pcapplusplus_script:
    - python3 -m pip install -r ci/run_tests/requirements.txt
    - python3 ci/run_tests/run_tests.py --interface eth0

#task:
#  name: Test Zstd MacOS
#  macos_instance:
#    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.1
#  configure_script:
#    - brew install zstd
#    - ./configure-mac_os_x.sh --use-zstd
#  build_script:
#    - make all
#  install_tcpreplay_script:
#    - brew install tcpreplay
#  test_pcapplusplus_script:
#    - python3 -m ensurepip
#    - python3 -m pip install -r ci/run_tests/requirements.txt
#    - python3 ci/run_tests/run_tests.py --interface en0 --use-sudo --test-args="-x TestPcapLiveDeviceSpecialCfg"

task:
  name: Test Zstd MacOS w/ CMake
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.1
  configure_script:
    - brew install zstd
    - cmake -DLIGHT_PCAPNG_ZSTD=ON -S . -B Dist
  build_script:
    - cmake --build Dist -j
  install_tcpreplay_script:
    - brew install tcpreplay
  test_pcapplusplus_script:
    - python3 -m ensurepip
    - python3 -m pip install -r ci/run_tests/requirements.txt
    - python3 ci/run_tests/run_tests.py --interface en0 --use-sudo --test-args="-x TestPcapLiveDeviceSpecialCfg"

task:
  name: Regression Tests Linux (Address Sanitizer)
  container:
    image: seladb/ubuntu2004:latest
  configure_script:
    - cmake -S . -B $BUILD_DIR
  test_script:
    - ctest -S $BUILD_DIR/asan-testing.cmake --verbose

task:
  name: Regression Tests Linux (Memory Sanitizer)
  container:
    image: seladb/ubuntu2004:latest
  configure_script:
    - cmake -S . -B $BUILD_DIR
  test_script:
    - ctest -S $BUILD_DIR/msan-testing.cmake --verbose

task:
  name: Regression Tests Linux (Thread Sanitizer)
  container:
    image: seladb/ubuntu2004:latest
  configure_script:
    - cmake -S . -B $BUILD_DIR
  test_script:
    - ctest -S $BUILD_DIR/tsan-testing.cmake --verbose

task:
  name: Regression Tests Linux (Undefined Behavior Sanitizer)
  container:
    image: seladb/ubuntu2004:latest
  configure_script:
    - cmake -S . -B $BUILD_DIR
  test_script:
    - ctest -S $BUILD_DIR/ubsan-testing.cmake --verbose

task:
  name: Build Doxygen Documentation
  container:
    image: seladb/ubuntu1804:latest
  env:
    - GITHUB_EMAIL: ENCRYPTED[ae4956ec74c9f329f7787cdfe3a6b5842870659275d0a9b513a0f6e64cd9c71cd2eb64219a9dc695f446fbd93c48fb04]
    - GITHUB_TOKEN: ENCRYPTED[ab88249da2005c70f25f5910b08e907139f73bc0efb31a19b33f832e9e3bffe3cfc8e81932f21d7734c7aceca2a77188]
  get_code_script:
    - git clone https://github.com/PcapPlusPlus/pcapplusplus.github.io.git
  configure_script:
    - ./configure-linux.sh --default
  build_script:
    - make libs
  build_documentation_script:
    - cd pcapplusplus.github.io/static/api-docs/next/doxygen
    - doxygen Doxyfile-ci
  upload_documentation_script: |
    if [ "$CIRRUS_BRANCH" == "master" -a "$CIRRUS_REPO_OWNER" == "seladb" ]; then
      find pcapplusplus.github.io/static/api-docs/next/ -maxdepth 1 -type f -exec rm {} \;
      rm -rf pcapplusplus.github.io/static/api-docs/next/search/
      mv pcapplusplus.github.io/static/api-docs/next/html/* pcapplusplus.github.io/static/api-docs/next/
      cd pcapplusplus.github.io/static/api-docs/next/
      git config user.name "seladb"
      git config user.email "${GITHUB_EMAIL}"
      git add .
      git commit -m "Update API documentation for commit ${CIRRUS_CHANGE_IN_REPO}"
      git push --quiet "https://${GITHUB_TOKEN}@github.com/PcapPlusPlus/pcapplusplus.github.io" master
    fi
