task:
  name: Test FreeBSD
  freebsd_instance:
    matrix:
      image_family: freebsd-11-3-snap
      image_family: freebsd-12-0
  update_script: pkg update -f
  install_script: pkg install -y libpcap bash gsed gmake
  configure_script:
    - ./configure-freebsd.sh --default
  build_script:
    - gmake all
  test_script:
    - cd Tests/Packet++Test && Bin/Packet++Test
    - cd ../Pcap++Test && sudo Bin/Pcap++Test -n
