coverage:
  status:
    project:
      default:
        threshold: 1%
    patch: off

codecov:
  notify:
    after_n_builds: 19
    wait_for_ci: yes

ignore:
  - "3rdParty/*"
  - "Tests/*"
  - "Examples/*"
