[files]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true
extend-exclude = [  "*.toml",
                    "*.dat",
                    "*Makefile*", 
                    "codespell-ignore-list.txt",
                    "ci",
                    "Dist",
                    "mk",
                    "Tests/Fuzzers/RegressionTests/regression_samples",
                    "Tests/ExamplesTest/expected_output",
                    "Tests/ExamplesTest/pcap_examples",
                    "Tests/Packet++Test/PacketExamples",
                    "Tests/Pcap++Test/PcapExamples",
                    "Tests/Packet++Test/Tests/SipSdpTests.cpp"]

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"

[default.extend-identifiers]

[default.extend-words]
ue = "ue"
loca = "loca"
inout = "inout"
ede = "ede"
tha = "tha"
gost = "gost"
ba = "ba"

[type.rust]
extend-glob = ["Cargo.toml"]

[type.rust.extend-identifiers]

[type.rust.extend-words]
flate = "flate"
ser = "ser"

[type.python]
extend-glob = ["pyproject.toml"]

[type.lock]
extend-glob = []
check-file = false

[type.cert]
extend-glob = [
    "*.crt",
    "*.cer",
    "*.ca-bundle",
    "*.p7b",
    "*.p7c",
    "*.p7s",
    "*.pem",
    "*.key",
    "*.keystore",
    "*.jks",
    "*.p12",
    "*.pfx",
    "*.pem",
]
check-file = false
