sudo: required
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode10.1
    - os: osx
      compiler: clang
      osx_image: xcode11.3

before_script:
  - ./configure-mac_os_x.sh

install:
  - python3 -m pip install -U pip;
  - python3 -m pip install -r Tests/ExamplesTest/requirements.txt;

script:
  - ERR_CODE=0
  - make all || ERR_CODE=$?;
  - cd Tests/Packet++Test && Bin/Packet++Test || ERR_CODE=$?;
  - cd ../Pcap++Test && sudo Bin/Pcap++Test -n || ERR_CODE=$?;
  - source ../../ci/find_ip_mac.sh;
  - cd ../ExamplesTest && python3 -m pytest --interface $NETWORK_IP --use-sudo || ERR_CODE=$?;
  - cd ../../ && sudo make install || ERR_CODE=$?;
  - (exit $ERR_CODE)

after_success:
  - cd Examples/Tutorials/Tutorial-HelloWorld/;
  - make -f Makefile.non_windows all;
  - ./Tutorial-HelloWorld;
