include ../../../Dist/mk/PcapPlusPlus.mk

# All Target
all:
	$(CXX) $(PCAPPP_BUILD_FLAGS) $(PCAPPP_INCLUDES) -c -o main.o main.cpp
	$(CXX) $(PCAPPP_LIBS_DIR) -static-libgcc -static-libstdc++ -o Tutorial-PacketCraftAndEdit.exe main.o $(PCAPPP_LIBS)

# Clean Target
clean:
	del main.o
	del Tutorial-PacketCraftAndEdit.exe
