name: Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: seladb/${{ matrix.image }}
    strategy:
      matrix:
       include:
         - image: ubuntu2004
           python: python3
         - image: ubuntu1804
           python: python3.8
         - image: ubuntu1604
           python: python3.8
         - image: centos7
           python: python3.8
         - image: fedora29
           python: python3

    steps:
    - name: Check linux version
      run: cat /etc/*-release

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Configure PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./configure-linux.sh --default

    - name: Build PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make all

    - name: Test Packet++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests/Packet++Test
        Bin/Packet++Test

    - name: Test Pcap++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests/Pcap++Test
        Bin/Pcap++Test -n

    - name: Test Examples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests/ExamplesTest
        ${{ matrix.python }} -m pip install -r requirements.txt
        ${{ matrix.python }} -m pytest

    - name: Build Tutorials
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Examples/Tutorials/Tutorial-HelloWorld
        make -f Makefile.non_windows all
        ./Tutorial-HelloWorld