name: Linux
on: [push]

jobs:
  build:
    container: seladb/ubuntu2004
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Configure PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./configure-linux.sh --default
