name: MinGW-w64
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        # install: base-devel mingw-w64-i686-gcc mingw-w64-i686-make
        install: mingw-w64-i686-gcc mingw-w64-i686-make

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install NPcap
      env:
        NPCAP_USERNAME: ${{ secrets.NPCAP_USERNAME }}
        NPCAP_PASSWORD: ${{ secrets.NPCAP_PASSWORD }}
      run: |
        ci\install_npcap.bat
        echo "PCAP_SDK_DIR=/C/Npcap-sdk" >> $env:GITHUB_ENV

    - name: List all dirs under msys\mingw32
      run: |
        Get-ChildItem -Path  D:\a\_temp\msys\msys64\mingw32\bin

    # - name: List all dirs under msys
    #   run: Get-ChildItem -Path  D:\a\_temp\msys\msys64\ -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName

    # - name: List all dirs under choco
    #   run: Get-ChildItem -Path C:\ProgramData\chocolatey\lib\mingw -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName

    - name: Configure PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: msys2 {0}
      run: ./configure-windows-mingw.bat mingw-w64 -m /mingw32 -w ${{ env.PCAP_SDK_DIR }} -s .

    # - name: Configure PcapPlusPlus
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: ./configure-windows-mingw.bat mingw-w64 -m D:\a\_temp\msys\msys64\mingw32 -w ${{ env.PCAP_SDK_DIR }} -s D:\a\_temp\msys\msys64


    - name: Build PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: msys2 {0}
      run: mingw32-make all

    - name: Test Packet++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\Packet++Test
        Bin\Packet++Test.exe

    - name: Test Pcap++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\Pcap++Test
        Bin\Pcap++Test.exe -n

    - name: Test Examples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\ExamplesTest
        python -m pip install -r requirements.txt
        python -m pytest
