name: Visual Studio

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       include:
        #  - vs-version: vs2019
        #    os: windows-2019
        #    platform: x64
        #    config: Release
         - vs-version: vs2019
           os: windows-2019
           platform: x86
           config: Debug
           pcap_lib: npcap
           use_zstd: true
        #  - vs-version: vs2017
        #    os: windows-2016
        #    platform: x86
        #    config: Release
        #    pcap_lib: npcap
        #  - vs-version: vs2017
        #    os: windows-2016
        #    platform: x64
        #    config: Debug

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Install WinPcap
      run: |
        ci\install_winpcap.bat
        echo "PCAP_SDK_DIR=C:\WpdPack" >> $env:GITHUB_ENV
      if: matrix.pcap_lib != 'npcap'

    - name: Install NPcap
      run: |
        ci\install_npcap.bat
        echo "PCAP_SDK_DIR=C:\Npcap-sdk" >> $env:GITHUB_ENV
      if: matrix.pcap_lib == 'npcap'

    - name: Download pthreads
      run: |
        git clone https://github.com/seladb/PcapPlusPlus-Deploy
        cd PcapPlusPlus-Deploy\Packages
        7z x pthreads-w32-2-9-1-release.zip -oC:\pthreads

    - name: Use Zstd
      run: |
        echo "$env:ChocolateyInstall"
        dir C:\ProgramData\chocolatey\Zstandard
        dir C:\ProgramData\chocolatey\Zstd
      if: matrix.use_zstd == true

    - name: Configure PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./configure-windows-visual-studio.bat -v ${{matrix.vs-version}} -w ${{ env.PCAP_SDK_DIR }} -p C:\pthreads

    - name: Build PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m mk\${{matrix.vs-version}}\PcapPlusPlus.sln /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}

    - name: Build Examples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m mk\${{matrix.vs-version}}\PcapPlusPlus-Examples.sln /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}

    - name: Build Tutorials
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m mk\${{matrix.vs-version}}\Tutorials.sln /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}

    - name: Test Packet++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\Packet++Test
        Bin\Packet++Test.exe

    - name: Test Pcap++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\Pcap++Test
        Bin\Pcap++Test.exe -n

    - name: Test Examples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\ExamplesTest
        python -m pip install -r requirements.txt
        python -m pytest
