name: Visual Studio

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       include:
        #  - vs-version: vs2019
        #    os: windows-2019
        #    platform: x64
        #    config: Release
         - vs-version: vs2019
           os: windows-2019
           platform: x86
           config: Debug
           pcap_lib: npcap
        #  - vs-version: vs2017
        #    os: windows-2016
        #    platform: x86
        #    config: Release
        #    pcap_lib: npcap
        #  - vs-version: vs2017
        #    os: windows-2016
        #    platform: x64
        #    config: Debug

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Install WinPcap
      run: |
        git clone https://github.com/mfontanini/winpcap-installer.git
        cd winpcap-installer
        ./winpcap-boundary-meter-4.1.3.exe /S
      if: matrix.pcap_lib != 'npcap'

    - name: Download WinPcap SDK
      uses: carlosperate/download-file-action@v1.0.3
      id: download-winpcap-sdk
      with:
        file-url: 'http://www.winpcap.org/install/bin/WpdPack_4_1_2.zip'
        file-name: 'WpdPack_4_1_2.zip'
      if: matrix.pcap_lib != 'npcap'

    - name: Extract WinPcap SDK
      run: 7z x ${{ steps.download-winpcap-sdk.outputs.file-path }} -oc:\
      if: matrix.pcap_lib != 'npcap'

    - name: Install NPcap
      run: ci\install_npcap.bat
      if: matrix.pcap_lib == 'npcap'

    - name: Download pthreads
      run: |
        git clone https://github.com/seladb/PcapPlusPlus-Deploy
        cd PcapPlusPlus-Deploy\Packages
        7z x pthreads-w32-2-9-1-release.zip -oC:\pthreads

    - name: Configure PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./configure-windows-visual-studio.bat -v ${{matrix.vs-version}} -w C:\WpdPack -p C:\pthreads

    - name: Build PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m mk\${{matrix.vs-version}}\PcapPlusPlus.sln /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}

    - name: Build Examples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m mk\${{matrix.vs-version}}\PcapPlusPlus-Examples.sln /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}

    - name: Build Tutorials
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m mk\${{matrix.vs-version}}\Tutorials.sln /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}

    - name: Test Packet++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\Packet++Test
        Bin\Packet++Test.exe

    - name: Test Pcap++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\Pcap++Test
        Bin\Pcap++Test.exe -n

    - name: Test Examples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests\ExamplesTest
        python -m pip install -r requirements.txt
        python -m pytest
