name: PF_RING
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: seladb/ubuntu1604-pfring

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./configure-linux.sh --pf-ring --pf-ring-home /PF_RING

    - name: Build PcapPlusPlus
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make all

    - name: Test Packet++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests/Packet++Test
        Bin/Packet++Test

    - name: Test Pcap++
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd Tests/Pcap++Test
        Bin/Pcap++Test -n
